version: '3.8'
services:
  backend:
    image: matheshwarsr/backend:latest
    ports:
      - "5000:5000"
  frontend:
    image: matheshwarsr/frontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
